In [26]:

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix
from sklearn.naive_bayes import GaussianNB,BernoulliNB,MultinomialNB
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_selection import SelectPercentile

# Naive Bayes

In [41]:
data = pd.read_csv('spam.csv',encoding='latin-1')
data.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

In [28]:
data.shape

(5572, 5)

In [29]:
data.drop(['Unnamed: 2',
'Unnamed: 3',
'Unnamed: 4'],axis=1,inplace = True)

In [33]:
data.head()

     v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [34]:
X_train,X_test,y_train,y_test = train_test_split(data.v2,data.v1,test_size=0.5,random_state=10)

In [42]:
vectorizer = TfidfVectorizer() # Term Frequency

In [44]:
X_train_transformed = vectorizer.fit_transform(X_train)
X_test_transformed = vectorizer.transform(X_test)
X_train_transformed

<2786x5990 sparse matrix of type '<class 'numpy.float64'>'
	with 36945 stored elements in Compressed Sparse Row format>

In [45]:

feature_names = vectorizer.get_feature_names()

In [38]:
feature_names # Every email contains the predictor

['00',
 '000',
 '000pes',
 '0121',
 '01223585334',
 '02',
 '0207',
 '02072069400',
 '02073162414',
 '021',
 '03',
 '04',
 '05',
 '0578',
 '06',
 '07',
 '07008009200',
 '07046744435',
 '07090201529',
 '07123456789',
 '0721072',
 '07732584351',
 '07734396839',
 '07742676969',
 '0776xxxxxxx',
 '07781482378',
 '07786200117',
 '07808',
 '07808247860',
 '07815296484',
 '07821230901',
 '07880867867',
 '0789xxxxxxx',
 '07946746291',
 '0796xxxxxx',
 '07973788240',
 '07xxxxxxxxx',
 '08',
 '0800',
 '08000407165',
 '08000776320',
 '08000839402',
 '08000930705',
 '08000938767',
 '08001950382',
 '08002888812',
 '08002986030',
 '08002986906',
 '08002988890',
 '08006344447',
 '0808',
 '08081560665',
 '0825',
 '0844',
 '0845',
 '08452810073',
 '0870',
 '08700621170150p',
 '08701213186',
 '08701237397',
 '08701417012',
 '08701417012150p',
 '087016248',
 '08701752560',
 '087018728737',
 '0870241182716',
 '08702490080',
 '08702840625',
 '08704439680ts',
 '08706091795',
 '08707500020',
 '08707509020',
 '0870753331018',
 '08708034412',
 '08709222922',
 '08709501522',
 '08712101358',
 '0871212025016',
 '08712300220',
 '087123002209am',
 '08712400200',
 '08712400603',
 '08712402902',
 '08712404000',
 '08712405020',
 '08712460324',
 '08712466669',
 '0871277810710p',
 '08714712379',
 '08714714011',
 '08715203028',
 '08715203649',
 '08715203685',
 '08715203694',
 '08715705022',
 '08717111821',
 '08717168528',
 '0871750',
 '08717507382',
 '08717509990',
 '08717895698',
 '08718720201',
 '08718723815',
 '08718725756',
 '08718726270',
 '087187262701',
 '08718726970',
 '08718726971',
 '08718727868',
 '08718727870',
 '08718730666',
 '08718738001',
 '08718738002',
 '08718738034',
 '08719180248',
 '08719181503',
 '08719181513',
 '08719839835',
 '08719899217',
 '08719899229',
 '08719899230',
 '09',
 '09041940223',
 '09050000301',
 '09050000332',
 '09050000928',
 '09050001808',
 '09050002311',
 '09050005321',
 '09050090044',
 '09050280520',
 '09053750005',
 '09056242159',
 '09058091854',
 '09058094454',
 '09058094507',
 '09058094583',
 '09058094594',
 '09058094599',
 '09058095201',
 '09058097189',
 '09058097218',
 '09058098002',
 '09058099801',
 '09061104283',
 '09061209465',
 '09061213237',
 '09061221061',
 '09061221066',
 '09061701461',
 '09061701851',
 '09061702893',
 '09061743386',
 '09061743806',
 '09061744553',
 '09061790121',
 '09061790126',
 '09063440451',
 '09063458130',
 '09064011000',
 '09064012103',
 '09064012160',
 '09064017295',
 '09064019788',
 '09065069154',
 '09065171142',
 '09065174042',
 '09065394514',
 '09065989182',
 '09066350750',
 '09066358152',
 '09066358361',
 '09066361921',
 '09066362220',
 '09066362231',
 '09066364311',
 '09066364589',
 '09066368327',
 '09066368753',
 '09066380611',
 '09066612661',
 '09066660100',
 '09071512432',
 '09090900040',
 '09094646899',
 '09111032124',
 '09701213186',
 '0a',
 '0quit',
 '10',
 '100',
 '1000',
 '1000call',
 '1000s',
 '100percent',
 '1013',
 '1030',
 '10am',
 '10k',
 '10p',
 '11',
 '113',
 '1131',
 '114',
 '1172',
 '118p',
 '11mths',
 '11pm',
 '12',
 '121',
 '123',
 '125gift',
 '128',
 '12hours',
 '12hrs',
 '12mths',
 '13',
 '130',
 '1327',
 '139',
 '14',
 '1405',
 '140ppm',
 '145',
 '1450',
 '146tf150p',
 '14tcr',
 '15',
 '150',
 '1500',
 '150p',
 '150p16',
 '150pm',
 '150ppermesssubscription',
 '150ppm',
 '151',
 '153',
 '15541',
 '15pm',
 '16',
 '165',
 '1680',
 '169',
 '177',
 '18',
 '1843',
 '18p',
 '18yrs',
 '1956669',
 '1apple',
 '1cup',
 '1im',
 '1lemon',
 '1million',
 '1pm',
 '1st',
 '1st4terms',
 '1stone',
 '1thing',
 '1tulsi',
 '1winaweek',
 '1x150p',
 '20',
 '200',
 '2000',
 '2003',
 '2004',
 '2005',
 '200p',
 '2025050',
 '20p',
 '21',
 '21870000',
 '21st',
 '22',
 '220',
 '220cm2',
 '2309',
 '24',
 '24hrs',
 '25',
 '250',
 '250k',
 '255',
 '25p',
 '26',
 '2667',
 '26th',
 '27',
 '28',
 '28days',
 '28thfeb',
 '29',
 '2b',
 '2c',
 '2day',
 '2end',
 '2exit',
 '2find',
 '2getha',
 '2geva',
 '2go',
 '2gthr',
 '2kbsubject',
 '2lands',
 '2marrow',
 '2moro',
 '2morow',
 '2morrow',
 '2mro',
 '2mrw',
 '2nd',
 '2nhite',
 '2nights',
 '2nite',
 '2optout',
 '2stoptx',
 '2stoptxt',
 '2u',
 '2wks',
 '2wt',
 '2wu',
 '2yr',
 '30',
 '300',
 '300603t',
 '300p',
 '3030',
 '30apr',
 '30ish',
 '30pp',
 '31',
 '3100',
 '310303',
 '31p',
 '32',
 '32323',
 '33',
 '350',
 '3510i',
 '35p',
 '36504',
 '3680',
 '373',
 '38',
 '391784',
 '3d',
 '3days',
 '3g',
 '3gbp',
 '3hrs',
 '3lp',
 '3miles',
 '3mins',
 '3mobile',
 '3qxj9',
 '3rd',
 '3ss',
 '3uz',
 '3xx',
 '400',
 '400mins',
 '402',
 '40411',
 '40533',
 '40gb',
 '41685',
 '41782',
 '4217',
 '430',
 '434',
 '44',
 '440',
 '4403ldnw1a7rw18',
 '44345',
 '447797706009',
 '448712404000',
 '449050000301',
 '45',
 '450',
 '450p',
 '450pw',
 '45239',
 '45pm',
 '4742',
 '48',
 '48922',
 '49557',
 '4a',
 '4d',
 '4few',
 '4fil',
 '4get',
 '4give',
 '4got',
 '4info',
 '4jx',
 '4mths',
 '4t',
 '4th',
 '4the',
 '4thnov',
 '4txt',
 '4u',
 '4w',
 '4ward',
 '4xx26',
 '50',
 '500',
 '5000',
 '50ea',
 '50gbp',
 '50p',
 '50perwksub',
 '50pm',
 '50pmmorefrommobile2bremoved',
 '50s',
 '515',
 '5226',
 '526',
 '530',
 '54',
 '542',
 '5free',
 '5k',
 '5min',
 '5p',
 '5pm',
 '5th',
 '5wb',
 '5we',
 '5wq',
 '600',
 '6031',
 '60p',
 '61200',
 '6230',
 '62468',
 '62735',
 '630',
 '65',
 '674',
 '69200',
 '69669',
 '69696',
 '69698',
 '69866',
 '69876',
 '69888',
 '69911',
 '69969',
 '69988',
 '6days',
 '6hl',
 '6hrs',
 '6missed',
 '6pm',
 '6th',
 '6times',
 '6wu',
 '6zf',
 '700',
 '7250',
 '7250i',
 '731',
 '74355',
 '75',
 '750',
 '762',
 '7634',
 '7684',
 '77',
 '7732584351',
 '78',
 '786',
 '7876150ppm',
 '79',
 '7ish',
 '7mp',
 '7pm',
 '7th',
 '7ws',
 '7zs',
 '80',
 '800',
 '80062',
 '8007',
 '80082',
 '80160',
 '80182',
 '8027',
 '80488',
 '80878',
 '81010',
 '81151',
 '81303',
 '81618',
 '82050',
 '820554ad0a1705572711',
 '82277',
 '82324',
 '82468',
 '83021',
 '83039',
 '83049',
 '83110',
 '83118',
 '83222',
 '83355',
 '83383',
 '83435',
 '83600',
 '83738',
 '84',
 '84025',
 '84199',
 '84484',
 '85',
 '85023',
 '85069',
 '85222',
 '85233',
 '8552',
 '85555',
 '86021',
 '861',
 '864233',
 '86688',
 '86888',
 '87066',
 '87070',
 '87077',
 '87131',
 '8714714',
 '87239',
 '87575',
 '88039',
 '88088',
 '88222',
 '88600',
 '8883',
 '88877',
 '88888',
 '89080',
 '89105',
 '89123',
 '89545',
 '89555',
 '89693',
 '89938',
 '8am',
 '8p',
 '8pm',
 '8th',
 '8wp',
 '900',
 '9061100010',
 '9153',
 '945',
 '97n7qp',
 '99',
 '9ae',
 '9am',
 '9pm',
 '9t',
 '9th',
 '9yt',
 'a30',
 'aa',
 'aah',
 'aaniye',
 'aathi',
 'aberdeen',
 'abi',
 'ability',
 'abiola',
 'abj',
 'able',
 'about',
 'abroad',
 'absolutly',
 'abt',
 'abusers',
 'ac',
 'academic',
 'acc',
 'accenture',
 'accept',
 'access',
 'accessible',
 'accidant',
 'accident',
 'accidentally',
 'accommodationvouchers',
 'accomodations',
 'accordin',
 'accordingly',
 'account',
 'accounts',
 'achan',
 'ache',
 'achieve',
 'acid',
 'acknowledgement',
 'acnt',
 'across',
 'acted',
 'action',
 'activate',
 'active',
 'activities',
 'actor',
 'actual',
 'actually',
 'ad',
 'adam',
 'add',
 'addamsfa',
 'added',
 'addicted',
 'addie',
 'adding',
 'address',
 'adewale',
 'adjustable',
 'admirer',
 'admission',
 'admit',
 'adore',
 'adoring',
 'adp',
 'ads',
 'adult',
 'advance',
 'advice',
 'advise',
 'advisors',
 'aeronautics',
 'aeroplane',
 'affair',
 'affairs',
 'affection',
 'affections',
 'affidavit',
 'afghanistan',
 'afraid',
 'africa',
 'aft',
 'after',
 'afternon',
 'afternoon',
 'afternoons',
 'afterwards',
 'aftr',
 'again',
 'against',
 'agalla',
 'age',
 'age16',
 'age23',
 'ages',
 'agidhane',
 'ago',
 'agree',
 'ah',
 'aha',
 'ahead',
 'ahhh',
 'ahhhh',
 'ahmad',
 'aid',
 'aig',
 'aight',
 'aint',
 'air',
 'airport',
 'airtel',
 'aiya',
 'aiyah',
 'aiyar',
 'aiyo',
 'ajith',
 'ak',
 'aka',
 'al',
 'alaikkum',
 'alaipayuthe',
 'album',
 'alcohol',
 'alert',
 'alertfrom',
 'alerts',
 'aletter',
 'alex',
 'alfie',
 'algebra',
 'alian',
 'alibi',
 'all',
 'allah',
 'allow',
 'allows',
 'almost',
 'alone',
 'along',
 'alot',
 'already',
 'alright',
 'alrite',
 'also',
 'alter',
 'alternative',
 'although',
 'alto18',
 'aluable',
 'always',
 'alwys',
 'am',
 'amazing',
 'american',
 'ami',
 'amla',
 'amma',
 'ammo',
 'among',
 'amongst',
 'amount',
 'amp',
 'amrita',
 'amt',
 'amy',
 'an',
 'ana',
 'anal',
 'anand',
 'and',
 'andre',
 'andres',
 'andrews',
 'andros',
 'angels',
 'angry',
 'animation',
 'anna',
 'annie',
 'annoncement',
 'announced',
 'announcement',
 'annoying',
 'another',
 'ans',
 'ansr',
 'answer',
 'answered',
 'answering',
 'answers',
 'answr',
 'antha',
 'anthony',
 'anti',
 'any',
 'anybody',
 'anyhow',
 'anymore',
 'anyone',
 'anyplaces',
 'anythin',
 'anything',
 'anytime',
 'anyway',
 'anyways',
 'apart',
 'apartment',
 'apes',
 'apnt',
 'apo',
 'apologise',
 'apologize',
 'apology',
 'app',
 'apparently',
 'appear',
 'appendix',
 'applebees',
 'apples',
 'application',
 'apply',
 'applyed',
 'appointment',
 'appointments',
 'appreciate',
 'appreciated',
 'approaches',
 'approaching',
 'appropriate',
 'approx',
 'apps',
 'appt',
 'appy',
 'april',
 'aproach',
 'aptitude',
 'aquarius',
 'ar',
 'arcade',
 'archive',
 'ard',
 'are',
 'area',
 'aren',
 'arent',
 'arestaurant',
 'argentina',
 'argh',
 'argue',
 'argument',
 'arguments',
 'aries',
 'arise',
 'arises',
 'arithmetic',
 'arm',
 'armand',
 'arms',
 'arng',
 'arngd',
 'arnt',
 'around',
 'aroundn',
 'arrange',
 'arrested',
 'arrive',
 'arsenal',
 'art',
 'arty',
 'arun',
 'as',
 'asa',
 'asap',
 'asda',
 'ashes',
 'ashwini',
 'asia',
 'asian',
 'asjesus',
 'ask',
 'askd',
 'asked',
 'askin',
 'asking',
 'asks',
 'asleep',
 'asp',
 'ass',
 'assessment',
 'assume',
 'assumed',
 'asthma',
 'astoundingly',
 'astrology',
 'astronomer',
 'asusual',
 'at',
 'ate',
 'athletic',
 'athome',
 'atlanta',
 'atlast',
 'atleast',
 'atm',
 'attach',
 'attached',
 'attack',
 'attempt',
 'attend',
 'attributed',
 'atural',
 'auction',
 'audition',
 'august',
 'aunties',
 'aunts',
 'aunty',
 'australia',
 'authorise',
 'auto',
 'av',
 'available',
 'avalarr',
 'avatar',
 'ave',
 'avent',
 'avenue',
 'avin',
 'avo',
 'avoiding',
 'await',
 'awaiting',
 'awake',
 'award',
 'awarded',
 'away',
 'awesome',
 'axis',
 'ay',
 'ayn',
 'b4',
 'b4190604',
 'b4280703',
 'b4u',
 'b4utele',
 'babe',
 'babes',
 'baby',
 'babysit',
 'babysitting',
 'back',
 'backdoor',
 'backwards',
 'bad',
 'badass',
 'bag',
 'bags',
 'bahamas',
 'bailiff',
 'bajarangabali',
 'bak',
 'balance',
 'ball',
 'baller',
 'bam',
 'bang',
 'bangb',
 'bangbabes',
 'bank',
 'banks',
 'banned',
 'banneduk',
 'banter',
 'bar',
 'barbie',
 'barcelona',
 'barely',
 'barkleys',
 'barry',
 'base',
 'based',
 'bash',
 'basic',
 'basically',
 'basq',
 'bat',
 'batch',
 'batchlor',
 'bath',
 'bathe',
 'bathing',
 'batsman',
 'battery',
 'bay',
 'bb',
 'bbd',
 'bcaz',
 'bck',
 'bcm',
 'bcm1896wc1n3xx',
 'bcmsfwc1n3xx',
 'bcoz',
 'bcums',
 'bday',
 'be',
 'beach',
 'bear',
 'bears',
 'beatings',
 'beauties',
 'beautiful',
 'becaus',
 'because',
 'becausethey',
 'become',
 'becomes',
 'becoz',
 'bed',
 'bedrm',
 'bedroom',
 'been',
 'beer',
 'beers',
 'befor',
 'before',
 'beg',
 'beggar',
 'begging',
 'begin',
 'begins',
 'begun',
 'behalf',
 'behave',
 'behind',
 ...]

In [46]:
len(feature_names)

5990

In [47]:
selector = SelectPercentile(percentile=10)
selector.fit(X_train_transformed, y_train)
X_train_transformed = selector.transform(X_train_transformed).toarray()
X_test_transformed = selector.transform(X_test_transformed).toarray()

In [48]:
model_gaussiannb = GaussianNB()
model_gaussiannb.fit(X_train_transformed,y_train)
y_predict = model_gaussiannb.predict(X_test_transformed)
accuracy_score(y_test,y_predict)

0.9655419956927495

In [49]:
model_bernb = BernoulliNB()
model_bernb.fit(X_train_transformed,y_train)
y_predict = model_bernb.predict(X_test_transformed)
accuracy_score(y_test,y_predict)

0.9802584350323044

In [50]:
model_mulnb = MultinomialNB()
model_mulnb.fit(X_train_transformed,y_train)
y_predict = model_mulnb.predict(X_test_transformed)
accuracy_score(y_test,y_predict)

0.9292893036611629

In [51]:
pd.crosstab(y_test,y_predict)

col_0   ham  spam
v1
ham    2409     0
spam    197   180

In [53]:
newEmail = pd.Series(['free voucher entry win trip'])

In [54]:
newEmail

0    free voucher entry win trip
dtype: object

In [55]:
newEmail_transformed = vectorizer.transform(newEmail)
newEmail_transformed = selector.transform(newEmail_transformed).toarray()

In [56]:
model_bernb.predict(newEmail_transformed)

array(['spam'], dtype='<U4')